name: nuget-build-deploy
on:
  push:
    branches:
      - TestingSomeGHActionsStuff
  workflow_dispatch:

jobs:
  build:
    name: Build and Release 🏗️
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dotnet-version: ['9.0.x']
    steps:
      - name: Checkout Code 🛒
        run: |
          cat "$(github.head_ref)"
          cat "$(github.ref)"
          cat "$(github.ref_name)"
          cat "$(github.ref_type)"
