name: nuget-build-deploy
on:
  push:
    branches:
      - TestingSomeGHActionsStuff
  workflow_dispatch:

jobs:
  build:
    name: Build and Release 🏗️
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dotnet-version: ['9.0.x']
    steps:
      - name: Checkout Code 🛒
        if: ${{ github.ref_type == 'branch' }}
        shell: bash
        run: |
          echo "${{github.head_ref}}"
          echo "${{github.ref}}"
          echo "${{github.ref_name}}"
          echo "${{github.ref_type}}"
