name: nuget-build-deploy
on:
  push:
    branches:
      - main
      - release/**
      - develop/**
    tags:
      - '\d+\.\d+\.\d+'
    paths-ignore:
      - '**/*.md'
      - 'LICENCE'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release 🏗️
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dotnet-version: ['10.0.x']
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup .NET ${{ matrix.dotnet-version }} 👟👟
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version 🆚
        run: dotnet --version
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x' # Or specify '6.0.x' for latest
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
      - name: Use Version
        run: |
          echo "The calculated version is: ${{ steps.gitversion.outputs.semVer }}"
          echo "Major.Minor.Patch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo $GITHUB_WORKSPACE
      - name: make directories
        run: |
          artifacts_subdirectory="artifacts"
          artifacts_directory="$GITHUB_WORKSPACE/$artifacts_subdirectory"
          nuget_directory="$artifacts_directory/nuget"
          echo "$nuget_directory"
          mkdir $artifacts_directory
          mkdir $nuget_directory
      - name: build it
        run: |
          ./build_custom.sh
